baseURL = "https://podcasting-guide.netlify.app"
languageCode = "hi-IN"
title = "पॉडकास्टिंग कैसे करें? - नये पॉडकास्टर्स के लिये संपूर्ण मार्गदर्शिका"
theme = "book-promo"
#disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  author = "Debashish Chakrabarty"
  description = "क्या आपके पास कहने के लिए कुछ खास है? अब उसे सुनने वाले भी होंगे। हर कहानी, हर विचार और हर आवाज़ को मंच मिले, यही है पॉडकास्टिंग का मकसद। इस पुस्तक से सीखिए कि बिना स्टूडियो, बिना खर्च और बिना तकनीकी ज्ञान के भी कैसे आप हज़ारों श्रोताओं तक अपनी बात पहुँचा सकते हैं। अपनी आवाज़ को शक्ति दीजिए, और खुद को एक सफल पॉडकास्टर बनाइए।"
  bookTitle = "पॉडकास्टिंग कैसे करें?"
  bookTagline = "नये पॉडकास्टर्स के लिये संपूर्ण मार्गदर्शिका!"
  coverImage = "/images/book-cover.jpg"
  getCopyText = "अपनी प्रति खरीदें"
  readSampleText = "पुस्तक की एक झलक"
  buyLink = "#buy-now"
  sampleLink = "#sneak-peek"
  googleAnalytics = "G-BFFJV3NVMD"
  keywords = "हिंदी पॉडकास्ट गाइड पॉडकास्टिंग कैसे करें भारत में पॉडकास्टिंग हिंदी ऑडियो कंटेंट पॉडकास्ट बनाने का तरीका पॉडकास्टिंग टिप्स माइक्रोफोन कैसे चुनें हिंदी पॉडकास्टर पॉडकास्ट स्क्रिप्टिंग हिंदी में पॉडकास्ट रिकॉर्डिंग गाइड मुफ्त पॉडकास्ट टूल्स पॉडकास्ट होस्टिंग इंडिया पॉडकास्ट वितरण Spotify पर पॉडकास्ट डालें पॉडकास्ट एप्स हिंदी पॉडकास्ट मार्केटिंग पॉडकास्ट से पैसे कमाना इंडियन पॉडकास्टर्स पॉडकास्ट विषय विचार पॉडकास्ट SEO हिंदी पॉडकास्ट प्रमोशन पॉडकास्ट एडिटिंग हिंदी में पॉडकास्ट एपिसोड प्लानिंग पॉडकास्ट टाइटल पॉडकास्ट इंट्रो आउट्रो बनाएँ पॉडकास्ट ब्रांडिंग पॉडकास्ट थंबनेल हिंदी पॉडकास्टिंग कोर्स पॉडकास्टिंग ईबुक इंडिया डिजिटल ऑडियो क्रिएटर्स आवाज़ से कहानी सुनाना पॉडकास्ट इंटरव्यू टिप्स पॉडकास्ट इतिहास भारत में डिजिटल मीडिया हिंदी में कंटेंट बनाना पॉडकास्ट नेटवर्क इंडिया रीजनल पॉडकास्ट हिंदी स्टोरीटेलिंग ऑडियो स्टोरीटेलिंग वोकल ट्रेनिंग पॉडकास्ट मोनेटाइजेशन देसी पॉडकास्टर्स हिंदी रेडियो स्टाइल पॉडकास्ट मोबाइल से पॉडकास्ट रिकॉर्ड करें पॉडकास्ट फॉर्मेट स्क्रिप्ट राइटिंग हिंदी पॉडकास्ट से आय podcasting in Hindi hindi podcast guide how to start a podcast in India hindi podcast creation audio storytelling in Hindi Indian podcasters podcasting ebook podcasting tips podcast marketing India podcast monetization tools for podcasting in Hindi how to host podcast Hindi podcast recording guide Hindi podcast SEO make money from podcasting Hindi podcast scripts hindi podcast courses podcast distribution platforms India free podcasting tools mobile podcast setup record podcast on phone Hindi podcasting book regional language podcasting Indian audio creators content creation in Hindi how to launch a podcast India podcast script Hindi best hindi podcast topics vocal training for podcast storytelling podcast career podcast tools India List of 50 best free podcasting tools 6-month podcast success plan"
  isbn = "ISBN: 9789334292398"

[menu]
  [[menu.main]]
    name = "मुखपृष्ठ"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "पुस्तक के बारे में"
    url = "#about-book"
    weight = 2
  [[menu.main]]
    name = "झलक"
    url = "#sneak-peek"
    weight = 3
  [[menu.main]]
    name = "समीक्षाएं"
    url = "#testimonials"
    weight = 4
  [[menu.main]]
    name = "लेखक से मिलें"
    url = "#author"
    weight = 5
  [[menu.main]]
    name = "अभी खरीदें"
    url = "#buy-now"
    weight = 6
  [[menu.main]]
    name = "Podbharati"
    url = "https://podbharati.com"
    weight = 7	
